{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "spidersilk.fullname" . }}
  labels: {{- include "spidersilk.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels: {{- include "spidersilk.selectorLabels" . | nindent 6 }}
{{- end -}}
