apiVersion: v1
kind: Service
metadata:
  name: {{ include "spidersilk.fullname" . }}
  labels: {{- include "spidersilk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
  selector: {{- include "spidersilk.selectorLabels" . | nindent 4 }}
